### ISSUE TITLE
SyntaxError: Unexpected token ) when doing require('steem')

### ISSUE THREAD

**Issue by rahulgandhi** [adcpm/steem#18]
I've installed steem package using the following command
`npm install steem --save`

now when I do 

`var steem = require('steem');`

I get the following error:
`node_modules/steemauth/lib/steemit/types.js:457
        return this.validate(((() => {
                                ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (node_modules/steemauth/lib/steemit/operations.js:1:75)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)`

**Comment by fletchertyler914** [comment]
@rahulgandhi are you serving with node? require is for node and you can't use it with a static page.

**Comment by rahulgandhi** [comment]
@fletchertyler914 Hey! yes, I was serving with node. It turns out that I was using some other version of node. Switching to 6.x or 4.x solved the problems. 

Closing this issue.

Thanks.

**Comment by fletchertyler914** [comment]
Nice catch!
